DROP DATABASE IF EXISTS DB_SEIXAS;
CREATE DATABASE DB_SEIXAS;

USE DB_SEIXAS;


CREATE TABLE USUARIO (
IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT	
, NOME VARCHAR(100)
, CPF VARCHAR(13)
, DT_NASCIMENTO DATE 
, VALOR DOUBLE
);

CREATE TABLE APOSTA (
  IDAPOSTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
, IDUSUARIO INT  
, VALOR1 DOUBLE
, VALOR2 DOUBLE
, VALOR3 DOUBLE
, VALOR4 DOUBLE
, FOREIGN KEY FK_IDUSUARIO (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)	
);

INSERT INTO `db_seixas`.`usuario` (`IDUSUARIO`, `NOME`, `VALOR`) VALUES ('1', 'Rodson', '20');
